disabled_rules:
  - todo
  - line_length
  - shorthand_operator
  - identifier_name
  - conditional_returns_on_newline
  - force_try
  - inclusive_language
opt_in_rules:
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - force_unwrapping 
  - implicit_return
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - FeedVerse/Data/Networking/Services/FeedServiceMock.swift
  
type_body_length:
  - 500 # warning
  - 800 # error
file_length:
  warning: 700
  error: 1200
identifier_name:
  min_length: # only min_length
    warning: 2 # only error
nesting:
  type_level:
    warning: 3

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
